[package]
name = "puzzle-solver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "api/main.rs"

[dependencies]
puzzle-utils = "0.3.0"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.38.0"
vercel_runtime = "1.1.4"
